# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "SOMB / %s"
author: Vincent Martens
favicon: /img/favicon.jpg
description: Snapshot of my brain
port: 8083

# OG image
origin: https://simple-blog.nuejs.org
og: /img/og.jpg

navigation:
  header:
    - SOMB: /
    - Contact: /contact/

  footer:
    - © Vincent Martens: /

    - image: /img/twitter.svg
      url: //x.com/vmartensHH
      alt: Twitter (X) profile
      size: 22 x 22

    - image: /img/github.svg
      url: //github.com/Neonize/SOMB
      alt: Github Project
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/vmartens
      alt: LinkedIn profile
      size: 22 x 22
